### ISSUE TITLE
Error in mde(x)  : 'list' object cannot be coerced to type 'double'

### ISSUE THREAD

**Issue by justin-olson** [dmuraka/spmoran#1]
This is such a cool package, I am excited to work with it. 

I've been working to implement the first model outlined in the sample code. I have been running into an issue using the package for a project. I have noticed that when I use the example code provided I receive the same error as my native code, so I think there may be an issue with the example code. 

When I read in the boston data set and run the esf function, I get the following error:

Error in mde(x) : 'list' object cannot be coerced to type 'double'

The only list object I have observed in the model is the 'meig' variable, which is a list. However, I am unable to resolve this error by inputting items from the meig list. I am hoping for your help in resolving this issue. Thanks in advance :)

**Comment by dmuraka** [comment]
Thank you very much for using this package (and sorry for the very late response. I overlooked it…). In my environment, the esf function works. I tested using versions 0.2.1 and 0.2.2. It might be a version problem. If the problem is not solved yet, please try the same code after updating this package.

Many thanks
