### ISSUE TITLE
How to interpret resf model results of estimate when the ng is log-Gaussian approximation? 

### ISSUE THREAD

**Issue by zhenchun** [dmuraka/spmoran#3]
I used the ```resf``` to model over-dispersed Poisson count data. After getting the model results, are the **estimates** log transformed? Should I transform them back using 10^**estimate** when I want to interpret the results? 

```
ng2<-nongauss_y(y_type="count", tr_num=2)

mod2<-resf(y = rate$n, x = rate$affluence_qnt, offset = log(rate$totpop13_17), meig=meig, nongauss=ng2, method="ml")

```

result:

Call:
resf(y = rate$n, x = rate$disadvantage_qnt, offset = log(rate$totpop13_17), 
    meig = meig, method = "ml", nongauss = ng2)

----Coefficients------------------------------
               **Estimate**         SE   t_value      p_value
(Intercept)  0.57882507 0.07588706  7.627455 7.327472e-14
V1          -0.03654534 0.02876536 -1.270464 2.043162e-01

----Variance parameter------------------------

Spatial effects (residuals):
                     (Intercept)
random_SE              0.7320979
Moran.I/max(Moran.I)   0.9414808

----Estimated probability distribution of y--------------
                Estimates
skewness         6.299121
excess kurtosis 49.854856
(dispersion parameter: 27.56421)

----Error statistics--------------------------
                                               stat
RMSE                                       39.93945
deviance explained (%)                     69.11161
Gaussian logLik approximating the model -1568.02062
AIC                                      3158.04124
BIC                                      3209.58571

NULL model: glm( y ~ x, offset = log( offset ), family = poisson )
   Gaussian loglik approximating the model: -1817.269
   ( AIC: 3644.538,  BIC: 3667.968 )

**Comment by dmuraka** [comment]
The estimated coefficients are for transformed y. You can use the coef_marginal function to interpret the estimated coefficients. The coef_marginal function evaluates summary statistics of d_y/d_x (Amount of increase in y when x increases by 1). Since d_y/d_x changes by sample, the mean or median are useful to interpret the result. Here is the sample code (Note: In this package, offset should NOT log-transformed a priori):

library(sf);library(rgeos);library(CARBayesdata);library(spdep);library(spmoran)

data("pollutionhealthdata")
head(pollutionhealthdata)

data("GGHB.IZ")
W.nb   <- poly2nb(GGHB.IZ)
W.list <- nb2listw(W.nb, style = "B")
W      <- nb2mat(W.nb, style = "B")

dat    <- pollutionhealthdata[pollutionhealthdata$year==2007,]
y      <- dat[,"observed"]
x      <- dat[,c("jsa","price","pm10")]
offset <- dat[,"expected"]        ### it should NOT log-transformed (unlike lm function))
ng     <- nongauss_y( y_type = "count", tr_num=2 )# log-transformation + 2 SAL transformation to improve accuracy

#### spatial Poisson regression
meig   <- meigen( cmat=W )
mod    <- resf(y=y, x=x, meig=meig, offset=offset,nongauss=ng)
coef_marginal(mod) # summary of d_y/d_x
mod$b  # regression coefficients

#### Poisson regression in the same setting
formula<- observed ~ jsa + price + pm10 + offset(log(expected))
mod0   <- glm(formula = formula, family = "quasipoisson",data = pollutionhealthdata)
summary(mod0)$coefficients # regression coefficients

**Comment by zhenchun** [comment]
Thank you very much for your detailed explanation. The note of "NOT log transformation offset" is important to me.
